apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  prometheus.yml: |
{{ .Files.Get "config/prometheus.yaml" | indent 4 }}

  alerts.yaml: |
{{ .Files.Get "config/alerts.yaml" | indent 4 }}